matrix:
  - name: markdown
    sources:
      - '**/*.md'
    dictionary:
      wordlists:
        - .dictionary
      output: .dict/custom.dic
    pipeline:
      - pyspelling.filters.markdown:
      - pyspelling.filters.html:
          comments: false
          attributes:
          - title
          - alt
          ignores:
          - code
          - pre
