name: Tests
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'master'

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  test:

    strategy:
      fail-fast: false

      matrix:
        os:
          - ubuntu-20.04
        ruby-version:
          - 2.5
          - 2.6
          - 2.7
        puppet-version:
          - 6.27.0
          - 7.17.0

    runs-on: ${{ matrix.os }}

    env:
      PUPPET_GEM_VERSION: "~> ${{ matrix.puppet-version }}"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install ruby dependencies
        run: bundle install
      - name: Run static code checks
        run: bundle exec rake validate lint rubocop
          # disable for now: check
      - name: Run parallel spec test
        run: bundle exec rake parallel_spec
